### PR TITLE
Manual add form

### PR DESCRIPTION
**Pull request by ghost**
In response to [Initiative 4 - What can I do?](https://noisebridge.net/wiki/Resources/Library#What_can_I_do.3F), I spent some time at 2169 to implement the manual add form. Some minor code changes included.

### CODE REVIEW

**Comment by robbintt** [comment]
Thank you for submitting this. This will be perfect combined with another change which is generalizing our records away from required ISBNs.  I will need to table this for 1-2 weeks as we get the other change synchronized and should have it in by the end of the month.  In the meantime can you please submit this on another branch and I can accept the PR to be integrated in master at that time?

**Comment by ghost** [comment]
@robbintt thanks! Should I have it submitted to the `newbook` branch, which is currently 18 commits behind?

**Comment by robbintt** [comment]
Can you make a new branch and submit the branch?





Best,

Trent Robbins
Tau Informatics LLC
desk: 415-404-9452
cell: 513-233-5651
trent@tauinformatics.com
@trentrobbins

**Comment by robbintt** [comment]
Can you make a new branch and submit the branch?

**Comment by ghost** [comment]
I don't think that it is possible on Github, unless you have the collaborator role/push access.

**Comment by robbintt** [comment]
here is a branch: https://github.com/robbintt/library-org/tree/manual-entry

**Comment by robbintt** [comment]
If you get a chance I recommend coming to the Digital Archivists meeting this month. There will be more discussion about the future direction of this app, there will be lots to do.

**Pull request closed without merging**
